### ISSUE TITLE
Contribution from defer

### ISSUE THREAD

**Issue by lbartnik** [r-lib/carrier#4]
Hi, I have recently learned about `carrier` and as far as I can tell it is an interesting attempt at solving a problem which I have also worked on. Since you mention possible future work to "figure [dependencies] out automatically" I thought I could contribute parts of my code that do just that.

There is a README file in the github repo (https://github.com/lbartnik/defer) that explains what is currently possible. If you find it useful, I'll be happy to work on merging relevant code into `carrier`

**Comment by lionel-** [comment]
Thanks for the proposal. However I think for automatic dependency packing, we prefer to use Henrik's globals package. So the scope of carrier is limited to explicit dependency packing.
